steps:
- id: 'bigquery'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      cd bigquery/
      terraform init
      terraform plan
      terraform apply -auto-approve
      cd ..
- id: 'pubsub'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      cd pubsub/
      terraform init
      terraform plan
      terraform apply -auto-approve
      cd ..
  waitFor: ['bigquery']
- id: 'storage'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      cd storage/
      terraform init
      terraform plan
      terraform apply -auto-approve
      cd ..
  waitFor: ['pubsub']
